name: shopping_app
description: "NTI__graduation__project__G4"
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.2.0
  dio: ^5.10.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  get_it: ^9.2.1
  injectable: ^3.0.0
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1 # dart run build_runner build --delete-conflicting-outputs
  injectable_generator: ^3.1.1
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
